version: '3.2'

services:

  database:
    image: dinited/oro-platform-database:3.1
    ports:
      - "3307:3306"

  php:
    volumes:
      - type: bind
        source: /opt/opv3
        target: /var/www/html/application

  websocket:
    volumes:
      - type: bind
        source: /opt/opv3
        target: /var/www/html/application

  webserver:
    volumes:
      - type: bind
        source: /opt/opv3
        target: /var/www/html/application
    ports:
      - "8307:80"

  debug:
    image: dinited/oro-platform-debug:3.1
    volumes:
      - type: bind
        source: /opt/opv3
        target: /var/www/html/application
    command:
      - /bin/sh
      - -c
      - |
        sleep 20
        rsync -ravz --delete /var/www/debug/ /var/www/html/application --exclude=".composer" --exclude="config/paramters.yml"
        mysql -u oro_db_user -poro_db_pass -h oro-platform-demo_database_1 -P 3306 opv3 -e "CREATE SCHEMA opv3;"
        mysql -u oro_db_user -poro_db_pass -h oro-platform-demo_database_1 -P 3306 opv3 < /var/www/debug/dump.sql
        tail -f /dev/null