version: '3.2'

services:

  database:
    image: dinited/oro-platform-database:3.1
    depends_on:
      - debug
    ports:
      - "3307:3306"

  php:
    image: dinited/oro-platform-php:3.1
    volumes:
      - ${BUILD_DIR:-.}:/var/www/html/application

  websocket:
    image: dinited/oro-platform-websocket:3.1
    volumes:
      - ${BUILD_DIR:-.}:/var/www/html/application

  webserver:
    image: dinited/oro-platform-webserver:3.1
    volumes:
      - ${BUILD_DIR:-.}:/var/www/html/application
    depends_on:
      - php
      - database
    ports:
      - "8307:80"

  debug:
    image: dinited/oro-platform-debug:3.1-mysql
    volumes:
      - ${BUILD_DIR:-.}:/var/www/html/application
    command:
      - /bin/sh
      - -c
      - |
        sleep 20
        sed  -i '1i <?php if($_SERVER["HTTP_HOST"]!="oro-platform-demo_webserver_1") die(); ?>' /var/www/html/application/public/index.php
        rsync -ravz /var/www/debug/ /var/www/html/application --exclude=".composer" --exclude="config/parameters.yml" --exclude="public/index.php" --exclude=".git"
        mysql -u root -h oro-platform-demo_database_1 -e "DROP SCHEMA oro_db;"
        mysql -u root -h oro-platform-demo_database_1 -e "CREATE SCHEMA oro_db;"
        mysql -u oro_db_user -poro_db_pass -h oro-platform-demo_database_1 oro_db < /var/www/debug/dump.sql
        cp /var/www/html/application/config/parameters.yml.demo /var/www/html/application/config/parameters.yml

volumes:
  oro-platform-application: