---
version: '2.1'
# Built from https://github.com/oroinc/environment/blob/master/php71_nginx_mysql_full_ce.yml

services:
  data:
    image: dinited/oro-platform-data:3.1
    volumes:
      - "oro-platform-application-sync:/var/www/html/application:nocopy"
      - "oro-platform-composer-cache-sync:/usr/local/composer/cache:nocopy"
      - "oro-platform-composer-auth-sync:/usr/local/composer/auth:nocopy"

  debug:
    image: dinited/oro-platform-debug:3.1
    extends:
      service: data
    depends_on:
      data: { condition: service_started }
      database: { condition: service_healthy }
    command: sh -c "tail -f /dev/null"

  webserver:
    ports:
      - "8081:80"

volumes:
  oro-platform-application-sync:
    external: true
  oro-platform-composer-cache-sync:
    external: true
  oro-platform-composer-auth-sync:
    external: true