version: '3.2'

volumes:
  opv31-demo:

services:

  database:
    image: dinited/oro-platform-database:3.1
    depends_on:
      - debug
    ports:
      - "${MYSQLPORT:-3307}:3306"

  php:
    image: dinited/oro-platform-php:3.1
    volumes:
      - ${VOLUME:-.build}:/var/www/html/application

  websocket:
    image: dinited/oro-platform-websocket:3.1
    volumes:
      - ${VOLUME:-.build}:/var/www/html/application

  webserver:
    image: dinited/oro-platform-webserver:3.1
    volumes:
      - ${VOLUME:-.build}:/var/www/html/application
    depends_on:
      - php
      - database
    ports:
      - "${WEBPORT:-8307}:80"

  debug:
    image: dinited/oro-platform-debug:3.1-installed
    volumes:
      - ${VOLUME:-.build}:/var/www/html/application
    command:
      - /bin/sh
      - -c
      - |
        cp /var/www/html/application/public/index.php /var/www/html/application/public/index.php.prod
        sed  -i '1i <?php if($_SERVER["HTTP_HOST"]!="oro-platform-demo_webserver_1") die("sync in progress"); ?>' /var/www/html/application/public/index.php
        rsync -ravz --delete /var/www/debug/ /var/www/html/application --exclude=".composer" --exclude="config/parameters.yml" --exclude=".git"
        sleep 20 # wait for database
        mysql -u root -h oro-platform-demo_database_1 -e "DROP SCHEMA oro_db;"
        mysql -u root -h oro-platform-demo_database_1 -e "CREATE SCHEMA oro_db;"
        mysql -u oro_db_user -poro_db_pass -h oro-platform-demo_database_1 oro_db < /var/www/debug/dump.sql
        cat >/var/www/html/application/config/parameters.yml <<'EOL'
        # This file is auto-generated during the composer install
        parameters:
            database_driver: pdo_mysql
            database_host: oro-platform-demo_database_1
            database_port: 3306
            database_name: oro_db
            database_user: oro_db_user
            database_password: oro_db_pass
            database_driver_options: {  }
            mailer_transport: mail
            mailer_host: 127.0.0.1
            mailer_port: null
            mailer_encryption: null
            mailer_user: null
            mailer_password: null
            websocket_bind_address: 0.0.0.0
            websocket_bind_port: 8080
            websocket_frontend_host: orocrm_websocket_1
            websocket_frontend_port: 8080
            websocket_frontend_path: ''
            websocket_backend_host: orocrm_websocket_1
            websocket_backend_port: 8080
            websocket_backend_path: ''
            websocket_backend_transport: tcp
            websocket_backend_ssl_context_options: {  }
            session_handler: session.handler.native_file
            locale: en
            secret: ThisTokenIsNotSoSecretChangeIt
            installed: '2019-10-22T00:03:34+00:00'
            assets_version: 8d4afed2
            assets_version_strategy: time_hash
            message_queue_transport: dbal
            message_queue_transport_config: null
        EOL
        cp /var/www/html/application/public/index.php.prod /var/www/html/application/public/index.php
        curl http://oro-platform-demo_webserver_1:80

