version: '3.2'

services:
  php:
    image: dinited/oro-platform-php:3.1

  websocket:
    image: dinited/oro-platform-websocket:3.1

  webserver:
    image: dinited/oro-platform-webserver:3.1

volumes:
  oro-platform-application: