version: '3.2'

services:
  database:
    image: dinited/oro-platform-database:3.1
    ports:
      - "3306:3306"

  php:
    volumes:
      - oro-platform-application-sync:/var/www/html/application:nocopy

  websocket:
    volumes:
      - oro-platform-application-sync:/var/www/html/application:nocopy

  webserver:
    volumes:
      - oro-platform-application-sync:/var/www/html/application:nocopy
    ports:
      - "8081:80"

  debug:
    image: dinited/oro-platform-debug:3.1
    volumes:
      - oro-platform-application-sync:/var/www/html/application:nocopy
    command:
      - /bin/sh
      - -c
      - |
        sleep 20
        rsync -ravz /var/www/debug/ /var/www/html/application --exclude=".git" --exclude=".gitignore" --exclude="composer.json" --exclude=".composer"
        mysql -u oro_db_user -poro_db_pass -h oro-platform_database_1 oro_db < /var/www/debug/dump.sql
        tail -f /dev/null

volumes:
  oro-platform-application-sync:
    external: true