version: '3.2'

services:

  database:
    image: dinited/oro-platform-database:3.1
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: oro_platform_db_3_1
      MYSQL_USER: oro_platform_db_user_3_1
      MYSQL_PASSWORD: oro_platform_db_pass_3_1
    ports:
      - "3307:3306"

  php:
    volumes:
      - type: bind
        source: /opt/opv3
        target: /var/www/html/application

  websocket:
    volumes:
      - type: bind
        source: /opt/opv3
        target: /var/www/html/application

  webserver:
    volumes:
      - type: bind
        source: /opt/opv3
        target: /var/www/html/application
    ports:
      - "8307:80"

  debug:
    image: dinited/oro-platform-debug:3.1
    volumes:
      - type: bind
        source: /opt/opv3
        target: /var/www/html/application
    command:
      - /bin/sh
      - -c
      - |
        sleep 20
        rsync -ravz --delete /var/www/debug/ /var/www/html/application --exclude=".composer"
        mysql -u oro_platform_db_user_3_1 -poro_platform_db_pass_3_1 -h -P 3307 oro_platform_demo -e "CREATE SCHEMA oro_platform_demo;"
        mysql -u oro_platform_db_user_3_1 -poro_platform_db_pass_3_1 -h -P 3307 oro_platform_demo < /var/www/debug/dump.sql
        tail -f /dev/null